import os
from pathlib import Path
from typing import Any, Callable, Dict, Optional

from src.domain.models import JobRequirement
from src.skills.base import BaseSkill
from src.skills.context import SkillExecutionContext
from src.skills.models import SkillResult, SkillSpec


class QueryRefineSkill(BaseSkill):
    spec = SkillSpec(
        name="query_refine",
        version="v1",
        description="Refine or rewrite a recruitment query/JD query",
        input_schema={
            "type": "object",
            "properties": {
                "query": {"type": "string"},
                "context": {"type": "string"},
                "metadata": {"type": "object"},
            },
            "required": ["query"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "refined_query": {"type": "string"},
                "reason": {"type": "string"},
                "metadata": {"type": "object"},
            },
            "required": ["refined_query"],
        },
        tags=["agent-adapter", "query-refine"],
    )

    def __init__(
        self,
        refine_callable: Optional[Callable[[Dict[str, Any], Optional[SkillExecutionContext]], Any]] = None,
        spec: Optional[SkillSpec] = None,
    ):
        super().__init__(spec=spec)
        self.refine_callable = refine_callable

    def run(self, input_data: Dict[str, Any], context: Optional[SkillExecutionContext] = None) -> SkillResult:
        query = input_data.get("query")
        if not isinstance(query, str) or not query.strip():
            raise ValueError("QueryRefineSkill requires input_data['query'] as a non-empty string")

        refine_callable = self.refine_callable or self._load_default_refine_callable()
        raw_output = refine_callable(input_data, context)
        output = self._normalize_output(raw_output)

        return SkillResult(
            skill_name=self.spec.name,
            version=self.spec.version,
            success=True,
            output=output,
        )

    def _load_default_refine_callable(self):
        try:
            from src.agents.refiner import RefinerAgent
        except Exception as exc:
            raise RuntimeError(f"Unable to lazy import RefinerAgent for QueryRefineSkill: {exc}") from exc

        try:
            refiner = RefinerAgent()
        except Exception as exc:
            raise RuntimeError(f"Unable to initialize RefinerAgent for QueryRefineSkill: {exc}") from exc

        def call_refiner(input_data: Dict[str, Any], context: Optional[SkillExecutionContext] = None):
            metadata = input_data.get("metadata") or {}
            state = {
                "extracted_jd": {"search_query": input_data["query"]},
                "refinement_advice": input_data.get("context", ""),
                "human_feedback": metadata.get("human_feedback", ""),
            }
            result = refiner(state)
            extracted_jd = result.get("extracted_jd", {})
            refined_query = extracted_jd.get("search_query")
            if not refined_query:
                raise RuntimeError("RefinerAgent did not return extracted_jd.search_query")
            return {
                "refined_query": refined_query,
                "reason": "Generated by RefinerAgent lazy adapter",
                "metadata": {"source": "RefinerAgent"},
            }

        return call_refiner

    def _normalize_output(self, raw_output: Any) -> Dict[str, Any]:
        if isinstance(raw_output, str):
            if not raw_output.strip():
                raise ValueError("QueryRefineSkill refine_callable returned an empty string")
            return {"refined_query": raw_output}

        if isinstance(raw_output, dict):
            refined_query = raw_output.get("refined_query")
            if not isinstance(refined_query, str) or not refined_query.strip():
                raise ValueError("QueryRefineSkill refine_callable dict output must include refined_query")
            output = {"refined_query": refined_query}
            if "reason" in raw_output:
                output["reason"] = raw_output["reason"]
            if "metadata" in raw_output:
                output["metadata"] = dict(raw_output["metadata"] or {})
            return output

        raise ValueError("QueryRefineSkill refine_callable must return a string or dict")


class PlannerExtractSkill(BaseSkill):
    spec = SkillSpec(
        name="planner_extract",
        version="v1",
        description="Extract structured job requirements from a raw JD or recruitment query",
        input_schema={
            "type": "object",
            "properties": {
                "raw_text": {"type": "string"},
                "metadata": {"type": "object"},
            },
            "required": ["raw_text"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "job_requirement": {"type": "object"},
                "extracted_keywords": {"type": "array"},
                "metadata": {"type": "object"},
            },
            "required": ["job_requirement"],
        },
        tags=["agent-adapter", "planner-extract"],
    )

    def __init__(
        self,
        extract_callable: Optional[Callable[[Dict[str, Any], Optional[SkillExecutionContext]], Any]] = None,
        spec: Optional[SkillSpec] = None,
    ):
        super().__init__(spec=spec)
        self.extract_callable = extract_callable

    def run(self, input_data: Dict[str, Any], context: Optional[SkillExecutionContext] = None) -> SkillResult:
        raw_text = input_data.get("raw_text")
        if not isinstance(raw_text, str) or not raw_text.strip():
            raise ValueError("PlannerExtractSkill requires input_data['raw_text'] as a non-empty string")

        extract_callable = self.extract_callable or self._load_default_extract_callable()
        raw_output = extract_callable(input_data, context)
        output = self._normalize_output(raw_output)

        return SkillResult(
            skill_name=self.spec.name,
            version=self.spec.version,
            success=True,
            output=output,
        )

    def _load_default_extract_callable(self):
        def call_planner(input_data: Dict[str, Any], context: Optional[SkillExecutionContext] = None):
            normalized = invoke_planner_agent_for_skill(
                raw_text=input_data["raw_text"],
                metadata={**dict(input_data.get("metadata") or {}), "source": "PlannerAgent"},
            )
            normalized.setdefault("metadata", {})["source"] = "PlannerAgent"
            return normalized

        return call_planner

    def _normalize_output(self, raw_output: Any) -> Dict[str, Any]:
        return normalize_planner_output_to_job_requirement(raw_output)


class RetrieverSkill(BaseSkill):
    spec = SkillSpec(
        name="resume_retrieve",
        version="v1",
        description="Retrieve candidate profiles, resume documents, or evidence for a job requirement/query",
        input_schema={
            "type": "object",
            "properties": {
                "query": {"type": "string"},
                "job_requirement": {"type": "object"},
                "top_k": {"type": "integer"},
                "metadata": {"type": "object"},
            },
        },
        output_schema={
            "type": "object",
            "properties": {
                "candidates": {"type": "array"},
                "resume_documents": {"type": "array"},
                "evidence": {"type": "array"},
                "metadata": {"type": "object"},
            },
        },
        tags=["agent-adapter", "resume-retrieve"],
    )

    def __init__(
        self,
        retrieve_callable: Optional[Callable[[Dict[str, Any], Optional[SkillExecutionContext]], Any]] = None,
        spec: Optional[SkillSpec] = None,
    ):
        super().__init__(spec=spec)
        self.retrieve_callable = retrieve_callable

    def run(self, input_data: Dict[str, Any], context: Optional[SkillExecutionContext] = None) -> SkillResult:
        query = input_data.get("query")
        job_requirement = input_data.get("job_requirement")
        if query is not None and not isinstance(query, str):
            raise ValueError("RetrieverSkill input_data['query'] must be a string when provided")
        if job_requirement is not None and not isinstance(job_requirement, dict):
            raise ValueError("RetrieverSkill input_data['job_requirement'] must be a dict when provided")
        if not query and not job_requirement:
            raise ValueError("RetrieverSkill requires at least query or job_requirement")

        retrieve_callable = self.retrieve_callable or self._load_default_retrieve_callable()
        raw_output = retrieve_callable(input_data, context)
        output = self._normalize_output(input_data, raw_output)

        return SkillResult(
            skill_name=self.spec.name,
            version=self.spec.version,
            success=True,
            output=output,
        )

    def _load_default_retrieve_callable(self):
        try:
            from src.agents.retriever import RetrieverAgent
        except Exception as exc:
            raise RuntimeError(f"Unable to lazy import RetrieverAgent for RetrieverSkill: {exc}") from exc

        try:
            retriever = RetrieverAgent()
        except Exception as exc:
            raise RuntimeError(f"Unable to initialize RetrieverAgent for RetrieverSkill: {exc}") from exc

        def call_retriever(input_data: Dict[str, Any], context: Optional[SkillExecutionContext] = None):
            job_requirement = dict(input_data.get("job_requirement") or {})
            if input_data.get("query"):
                job_requirement["search_query"] = input_data["query"]
            result = retriever({"extracted_jd": job_requirement})
            candidate_pool = result.get("candidate_pool", [])
            evidence = [
                {
                    "text": candidate.get("text", ""),
                    "metadata": candidate.get("metadata", {}),
                }
                for candidate in candidate_pool
            ]
            return {
                "evidence": evidence,
                "metadata": {"source": "RetrieverAgent"},
            }

        return call_retriever

    def _normalize_output(self, input_data: Dict[str, Any], raw_output: Any) -> Dict[str, Any]:
        if isinstance(raw_output, list):
            raw_output = {"evidence": raw_output}
        if not isinstance(raw_output, dict):
            raise ValueError("RetrieverSkill retrieve_callable must return a dict or list")

        output = {}
        for field_name in ("candidates", "resume_documents", "evidence"):
            if field_name in raw_output:
                value = raw_output[field_name]
                if not isinstance(value, list):
                    raise ValueError(f"RetrieverSkill output field {field_name} must be a list")
                output[field_name] = list(value)

        if not any(key in output for key in ("candidates", "resume_documents", "evidence")):
            raise ValueError("RetrieverSkill output must include candidates, resume_documents, or evidence")

        top_k = input_data.get("top_k")
        if isinstance(top_k, int) and top_k >= 0:
            for field_name in ("candidates", "resume_documents", "evidence"):
                if field_name in output:
                    output[field_name] = output[field_name][:top_k]

        if "metadata" in raw_output:
            output["metadata"] = dict(raw_output["metadata"] or {})
        return output


class CandidateMatchSkill(BaseSkill):
    spec = SkillSpec(
        name="candidate_match",
        version="v1",
        description="Score and explain the match between a job requirement and a candidate profile",
        input_schema={
            "type": "object",
            "properties": {
                "job_requirement": {"type": "object"},
                "candidate_profile": {"type": "object"},
                "evidence": {},
                "metadata": {"type": "object"},
            },
            "required": ["job_requirement", "candidate_profile"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "match_report": {"type": "object"},
                "total_score": {"type": "number"},
                "recommendation": {"type": "string"},
                "metadata": {"type": "object"},
            },
            "required": ["match_report", "total_score", "recommendation"],
        },
        tags=["agent-adapter", "candidate-match"],
    )

    def __init__(
        self,
        match_callable: Optional[Callable[[Dict[str, Any], Optional[SkillExecutionContext]], Dict[str, Any]]] = None,
        spec: Optional[SkillSpec] = None,
    ):
        super().__init__(spec=spec)
        self.match_callable = match_callable

    def run(self, input_data: Dict[str, Any], context: Optional[SkillExecutionContext] = None) -> SkillResult:
        job_requirement = input_data.get("job_requirement")
        candidate_profile = input_data.get("candidate_profile")
        if not isinstance(job_requirement, dict):
            raise ValueError("CandidateMatchSkill requires input_data['job_requirement'] as a dict")
        if not isinstance(candidate_profile, dict):
            raise ValueError("CandidateMatchSkill requires input_data['candidate_profile'] as a dict")

        match_callable = self.match_callable or self._load_default_match_callable()
        raw_output = match_callable(input_data, context)
        output = self._normalize_output(input_data, raw_output)

        return SkillResult(
            skill_name=self.spec.name,
            version=self.spec.version,
            success=True,
            output=output,
        )

    def _load_default_match_callable(self):
        try:
            from src.agents.matcher import MatcherAgent
        except Exception as exc:
            raise RuntimeError(f"Unable to lazy import MatcherAgent for CandidateMatchSkill: {exc}") from exc

        try:
            matcher = MatcherAgent()
        except Exception as exc:
            raise RuntimeError(f"Unable to initialize MatcherAgent for CandidateMatchSkill: {exc}") from exc

        def call_matcher(input_data: Dict[str, Any], context: Optional[SkillExecutionContext] = None):
            job_requirement = input_data["job_requirement"]
            candidate_profile = input_data["candidate_profile"]
            candidate_text = _candidate_profile_to_text(candidate_profile)
            state = {
                "extracted_jd": job_requirement,
                "candidate_pool": [{"text": candidate_text, "metadata": candidate_profile}],
                "loop_count": 0,
            }
            result = matcher(state)
            reports = result.get("final_reports", [])
            if not reports:
                raise RuntimeError("MatcherAgent did not return final_reports")
            report = dict(reports[0])
            return {
                "match_report": report,
                "total_score": report.get("total_score", 0),
                "recommendation": report.get("final_verdict", ""),
                "metadata": {"source": "MatcherAgent"},
            }

        return call_matcher

    def _normalize_output(self, input_data: Dict[str, Any], raw_output: Any) -> Dict[str, Any]:
        if not isinstance(raw_output, dict):
            raise ValueError("CandidateMatchSkill match_callable must return a dict")
        if "total_score" not in raw_output:
            raise ValueError("CandidateMatchSkill match_callable output must include total_score")

        total_score = _coerce_total_score(raw_output["total_score"])
        recommendation = str(raw_output.get("recommendation") or _recommendation_from_score(total_score))
        match_report = raw_output.get("match_report")
        if match_report is None:
            match_report = self._build_match_report(input_data, total_score, recommendation)
        elif not isinstance(match_report, dict):
            raise ValueError("CandidateMatchSkill match_report must be a dict")
        else:
            match_report = dict(match_report)
            match_report["total_score"] = total_score
            match_report.setdefault("recommendation", recommendation)

        candidate_profile = input_data.get("candidate_profile") if isinstance(input_data, dict) else {}
        if isinstance(candidate_profile, dict):
            candidate_id = str(candidate_profile.get("candidate_id") or "")
            candidate_name = _resolved_candidate_name(candidate_profile)
            if candidate_id:
                match_report["candidate_id"] = candidate_id
            if candidate_name and _is_placeholder_candidate_name(match_report.get("candidate_name")):
                match_report["candidate_name"] = candidate_name
            metadata = dict(match_report.get("metadata") or {})
            if candidate_id:
                metadata.setdefault("candidate_id", candidate_id)
            if candidate_name:
                metadata.setdefault("candidate_name", candidate_name)
            if metadata:
                match_report["metadata"] = metadata

        output = {
            "match_report": match_report,
            "total_score": total_score,
            "recommendation": recommendation,
        }
        if "metadata" in raw_output:
            output["metadata"] = dict(raw_output["metadata"] or {})
        return output

    def _build_match_report(
        self,
        input_data: Dict[str, Any],
        total_score: float,
        recommendation: str,
    ) -> Dict[str, Any]:
        job_requirement = input_data["job_requirement"]
        candidate_profile = input_data["candidate_profile"]
        evidence = input_data.get("evidence", [])
        if isinstance(evidence, dict):
            evidence_items = [str(value) for value in evidence.values()]
        elif isinstance(evidence, list):
            evidence_items = [str(item) for item in evidence]
        else:
            evidence_items = [str(evidence)]

        return {
            "job_id": job_requirement.get("job_id", ""),
            "candidate_id": candidate_profile.get("candidate_id", ""),
            "total_score": total_score,
            "dimension_scores": {},
            "strengths": [],
            "weaknesses": [],
            "evidence": evidence_items,
            "recommendation": recommendation,
            "metadata": {
                "source": "CandidateMatchSkill",
                "job_title": job_requirement.get("title", ""),
                "candidate_name": _resolved_candidate_name(candidate_profile),
            },
        }


def _coerce_total_score(value: Any) -> float:
    try:
        return float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError("CandidateMatchSkill total_score must be numeric") from exc


def _recommendation_from_score(total_score: float) -> str:
    if total_score >= 80:
        return "strong_match"
    if total_score >= 60:
        return "possible_match"
    return "not_recommended"


def _candidate_profile_to_text(candidate_profile: Dict[str, Any]) -> str:
    candidate_name = _resolved_candidate_name(candidate_profile)
    parts = [
        candidate_name,
        "Skills: " + ", ".join(candidate_profile.get("skills", [])),
        "Education: " + candidate_profile.get("education", ""),
        "Experience: " + "; ".join(candidate_profile.get("experience", [])),
        "Projects: " + "; ".join(candidate_profile.get("projects", [])),
    ]
    return "\n".join(part for part in parts if part.strip())


def _resolved_candidate_name(candidate_profile: Dict[str, Any]) -> str:
    for key in ("candidate_name", "name"):
        value = str(candidate_profile.get(key) or "").strip()
        if value and not _is_placeholder_candidate_name(value):
            return value[:64]
    return ""


def _is_placeholder_candidate_name(value: Any) -> bool:
    text = str(value or "").strip()
    if not text:
        return True
    normalized = text.replace(" ", "").replace("_", "").replace("-", "").lower()
    return normalized in {"未知", "未提供", "无", "none", "unknown", "n/a", "na", "简历", "resume", "cv"}


def normalize_planner_output_to_job_requirement(
    output: Any,
    *,
    raw_text: str = "",
    metadata: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Normalize production Planner-style output into PlannerExtractSkill output.

    The adapter keeps only schema-level fields needed by the skill workflow and
    never copies full LLM responses into diagnostics.
    """

    base_metadata = dict(metadata or {})
    if isinstance(output, JobRequirement):
        return {"job_requirement": output.to_dict()}
    if not isinstance(output, dict):
        raise ValueError("planner_schema_adapter_failed: observed_type=non_dict expected_keys=job_requirement|extracted_jd")

    raw_output = dict(output)
    raw_metadata = raw_output.get("metadata")
    if isinstance(raw_metadata, dict):
        base_metadata.update(raw_metadata)

    if "job_requirement" in raw_output:
        job_requirement = raw_output["job_requirement"]
        if isinstance(job_requirement, JobRequirement):
            job_requirement = job_requirement.to_dict()
        if not isinstance(job_requirement, dict):
            raise ValueError("planner_schema_adapter_failed: observed_keys=job_requirement expected_job_requirement=dict")
        normalized = {"job_requirement": _ensure_planner_requirement_shape(dict(job_requirement), raw_text, base_metadata)}
        if "extracted_keywords" in raw_output:
            normalized["extracted_keywords"] = _as_list(raw_output.get("extracted_keywords"))
        else:
            normalized["extracted_keywords"] = _as_list(normalized["job_requirement"].get("tech_stack"))
        if base_metadata:
            normalized["metadata"] = dict(base_metadata)
        return normalized

    if "extracted_jd" in raw_output:
        extracted = raw_output.get("extracted_jd")
        if not isinstance(extracted, dict):
            raise ValueError("planner_schema_adapter_failed: observed_keys=extracted_jd expected_extracted_jd=dict")
    elif _looks_like_planner_extracted_jd(raw_output):
        extracted = raw_output
    else:
        observed_keys = ",".join(sorted(str(key) for key in raw_output.keys()))
        raise ValueError(
            "planner_schema_adapter_failed: "
            f"observed_keys={observed_keys} expected_keys=job_requirement|extracted_jd|tech_stack|education|must_have|search_query"
        )

    job_requirement = _planner_extracted_to_job_requirement(
        raw_text=raw_text,
        extracted=dict(extracted),
        metadata=base_metadata,
    )
    normalized = {
        "job_requirement": job_requirement,
        "extracted_keywords": _as_list(raw_output.get("extracted_keywords") or extracted.get("tech_stack")),
    }
    if base_metadata:
        normalized["metadata"] = dict(base_metadata)
    return normalized


def build_planner_state_for_skill(raw_text: str) -> Dict[str, Any]:
    """Build the same minimal graph-state shape used by the production harness."""

    try:
        from src.core.state import create_initial_state
    except Exception as exc:
        raise RuntimeError(
            "planner_wrapper_failed "
            + _planner_invocation_markers(
                stage="build_state",
                raw_text=raw_text,
                provider_error_type=type(exc).__name__,
            )
        ) from exc

    try:
        return dict(create_initial_state(raw_text))
    except Exception as exc:
        raise RuntimeError(
            "planner_wrapper_failed "
            + _planner_invocation_markers(
                stage="build_state",
                raw_text=raw_text,
                provider_error_type=type(exc).__name__,
            )
        ) from exc


def invoke_planner_agent_for_skill(
    *,
    raw_text: str,
    metadata: Optional[Dict[str, Any]] = None,
    planner_factory: Optional[Callable[[], Any]] = None,
    allow_deterministic_fallback: bool = False,
) -> Dict[str, Any]:
    """Invoke PlannerAgent through a production-like state adapter.

    The helper is intentionally summary-safe on failure: exception messages,
    prompts, and full LLM output are not copied into the raised error string.
    """

    state = build_planner_state_for_skill(raw_text)
    try:
        planner = create_planner_agent_for_skill(
            planner_factory=planner_factory,
            state=state,
            raw_text=raw_text,
        )
    except Exception as exc:
        if allow_deterministic_fallback:
            return _deterministic_planner_fallback_output(
                raw_text=raw_text,
                metadata=metadata,
                provider_error_type=_extract_marker_value(str(exc), "provider_error_type") or type(exc).__name__,
            )
        raise

    try:
        raw_output = planner(state)
    except Exception as exc:
        if allow_deterministic_fallback:
            return _deterministic_planner_fallback_output(
                raw_text=raw_text,
                metadata=metadata,
                provider_error_type=type(exc).__name__,
            )
        raise RuntimeError(
            "planner_wrapper_failed "
            + _planner_invocation_markers(
                stage="invoke_planner_agent",
                state=state,
                raw_text=raw_text,
                provider_error_type=type(exc).__name__,
                provider_diagnostics=build_planner_provider_diagnostics(
                    provider_error_type=type(exc).__name__,
                    state=state,
                ),
            )
        ) from exc

    try:
        normalized = normalize_planner_output_to_job_requirement(
            raw_output,
            raw_text=raw_text,
            metadata={
                **dict(metadata or {}),
                "real_planner_invoked": True,
                "real_planner_failed": False,
                "planner_fallback_used": False,
                "planner_invocation_stage": "completed",
                "planner_raw_text_length": len(raw_text or ""),
            },
        )
        normalized.setdefault("metadata", {}).update(
            {
                "real_planner_invoked": True,
                "real_planner_failed": False,
                "planner_fallback_used": False,
                "planner_invocation_stage": "completed",
                "planner_raw_text_length": len(raw_text or ""),
            }
        )
        return normalized
    except Exception as exc:
        raise RuntimeError(
            "planner_wrapper_failed "
            + _planner_invocation_markers(
                stage="normalize_output",
                state=state,
                raw_text=raw_text,
                output=raw_output,
                provider_error_type=type(exc).__name__,
                provider_diagnostics=build_planner_provider_diagnostics(
                    provider_error_type=type(exc).__name__,
                    state=state,
                    output=raw_output,
                ),
            )
        ) from exc


def create_planner_agent_for_skill(
    *,
    planner_factory: Optional[Callable[[], Any]] = None,
    state: Optional[Dict[str, Any]] = None,
    raw_text: str = "",
) -> Any:
    if planner_factory is not None:
        try:
            return planner_factory()
        except Exception as exc:
            raise RuntimeError(
                "planner_wrapper_failed "
                + _planner_invocation_markers(
                    stage="instantiate_planner_agent",
                    state=state,
                    raw_text=raw_text,
                    provider_error_type=type(exc).__name__,
                    provider_diagnostics=build_planner_provider_diagnostics(
                        provider_error_type=type(exc).__name__,
                        state=state,
                    ),
                )
            ) from exc

    try:
        from src.agents.planner import PlannerAgent
    except Exception as exc:
        raise RuntimeError(
            "planner_wrapper_failed "
            + _planner_invocation_markers(
                stage="import_planner_agent",
                state=state,
                raw_text=raw_text,
                provider_error_type=type(exc).__name__,
                provider_diagnostics=build_planner_provider_diagnostics(
                    provider_error_type=type(exc).__name__,
                    state=state,
                ),
            )
        ) from exc

    try:
        return PlannerAgent()
    except Exception as exc:
        raise RuntimeError(
            "planner_wrapper_failed "
            + _planner_invocation_markers(
                stage="instantiate_planner_agent",
                state=state,
                raw_text=raw_text,
                provider_error_type=type(exc).__name__,
                provider_diagnostics=build_planner_provider_diagnostics(
                    provider_error_type=type(exc).__name__,
                    state=state,
                ),
            )
        ) from exc


def build_planner_provider_diagnostics(
    *,
    provider_error_type: str = "",
    state: Optional[Dict[str, Any]] = None,
    output: Any = None,
    load_dotenv: bool = False,
) -> Dict[str, Any]:
    dotenv_loaded: Any = "skip"
    dotenv_path_present = (Path(__file__).resolve().parents[2] / ".env").exists()
    if load_dotenv:
        try:
            from dotenv import load_dotenv

            dotenv_loaded = bool(load_dotenv())
        except Exception:
            dotenv_loaded = False
    try:
        from src.config import get_settings

        settings = get_settings()
        llm_model = str(settings.llm_model)
    except Exception:
        llm_model = ""
    state = dict(state or {})
    output_keys = []
    if isinstance(output, dict):
        output_keys = sorted(str(key) for key in output.keys())
    return {
        "dotenv_loaded": dotenv_loaded,
        "dotenv_path_present": bool(dotenv_path_present),
        "openai_api_key": "set" if os.environ.get("OPENAI_API_KEY") else "missing",
        "openai_api_base": "set" if os.environ.get("OPENAI_API_BASE") else "missing",
        "llm_model": llm_model,
        "planner_agent_class": "PlannerAgent",
        "invocation_method": "__call__",
        "state_shape_keys": sorted(str(key) for key in state.keys()),
        "output_keys": output_keys,
        "provider_error_type": str(provider_error_type or ""),
        "summary_only": True,
    }


def _planner_extracted_to_job_requirement(raw_text: str, extracted: Dict[str, Any], metadata: Dict[str, Any]) -> Dict[str, Any]:
    tech_stack = _as_list(extracted.get("tech_stack"))
    must_have = _as_list(extracted.get("must_have"))
    search_query = _as_string(extracted.get("search_query"))
    requirement = JobRequirement(
        raw_text=raw_text,
        required_skills=tech_stack,
        education=_as_string(extracted.get("education")),
        metadata={
            **metadata,
            "must_have": must_have,
            "search_query": search_query,
        },
    ).to_dict()
    requirement["tech_stack"] = tech_stack
    requirement["must_have"] = must_have
    requirement["search_query"] = search_query
    return requirement


def _ensure_planner_requirement_shape(job_requirement: Dict[str, Any], raw_text: str, metadata: Dict[str, Any]) -> Dict[str, Any]:
    normalized = dict(job_requirement)
    existing_metadata = dict(normalized.get("metadata") or {})
    merged_metadata = {**metadata, **existing_metadata}
    tech_stack = _as_list(
        normalized.get("tech_stack")
        or normalized.get("required_skills")
        or merged_metadata.get("tech_stack")
    )
    must_have = _as_list(normalized.get("must_have") or merged_metadata.get("must_have"))
    search_query = _as_string(normalized.get("search_query") or merged_metadata.get("search_query"))
    normalized.setdefault("raw_text", raw_text)
    normalized["required_skills"] = _as_list(normalized.get("required_skills") or tech_stack)
    normalized["tech_stack"] = tech_stack
    normalized["education"] = _as_string(normalized.get("education"))
    normalized["must_have"] = must_have
    normalized["search_query"] = search_query
    normalized["metadata"] = {
        **merged_metadata,
        "must_have": must_have,
        "search_query": search_query,
    }
    return normalized


def _looks_like_planner_extracted_jd(value: Dict[str, Any]) -> bool:
    planner_keys = {"tech_stack", "education", "must_have", "search_query"}
    return any(key in value for key in planner_keys)


def _planner_invocation_markers(
    *,
    stage: str,
    raw_text: str = "",
    state: Optional[Dict[str, Any]] = None,
    output: Any = None,
    provider_error_type: str = "",
    provider_diagnostics: Optional[Dict[str, Any]] = None,
) -> str:
    state = dict(state or {})
    input_keys = ",".join(sorted(str(key) for key in state.keys()))
    output_keys = ""
    if isinstance(output, dict):
        output_keys = ",".join(sorted(str(key) for key in output.keys()))
    markers = {
        "planner_invocation_stage": stage,
        "planner_input_keys": input_keys,
        "planner_has_messages": "true" if bool(state.get("messages")) else "false",
        "planner_raw_text_length": str(len(raw_text or "")),
        "planner_output_keys": output_keys,
        "provider_error_type": provider_error_type,
    }
    diagnostics = dict(provider_diagnostics or {})
    for key in (
        "dotenv_loaded",
        "dotenv_path_present",
        "openai_api_key",
        "openai_api_base",
        "llm_model",
        "planner_agent_class",
        "invocation_method",
    ):
        if key in diagnostics:
            markers[f"planner_provider_{key}"] = _marker_string(diagnostics.get(key))
    return " ".join(f"{key}={value}" for key, value in markers.items())


def _deterministic_planner_fallback_output(
    *,
    raw_text: str,
    metadata: Optional[Dict[str, Any]],
    provider_error_type: str,
) -> Dict[str, Any]:
    known = ["Python", "RAG", "LangGraph", "AI Agent", "LLM", "Chroma", "LlamaIndex"]
    lowered = (raw_text or "").lower()
    tech_stack = [skill for skill in known if skill.lower() in lowered]
    extracted = {
        "tech_stack": tech_stack,
        "education": "",
        "must_have": [],
        "search_query": " ".join(tech_stack),
    }
    fallback_metadata = {
        **dict(metadata or {}),
        "planner_fallback_used": True,
        "planner_fallback_type": "deterministic",
        "real_planner_invoked": True,
        "real_planner_failed": True,
        "provider_error_type": str(provider_error_type or ""),
        "summary_only": True,
    }
    normalized = normalize_planner_output_to_job_requirement(
        {"extracted_jd": extracted},
        raw_text=raw_text,
        metadata=fallback_metadata,
    )
    normalized.setdefault("metadata", {}).update(fallback_metadata)
    return normalized


def _marker_string(value: Any) -> str:
    if value is True:
        return "true"
    if value is False:
        return "false"
    text = str(value or "")
    return text.replace(" ", "_").replace("|", "_")


def _extract_marker_value(text: str, marker: str) -> str:
    token = f"{marker}="
    if token not in text:
        return ""
    return text.split(token, 1)[1].split(" ", 1)[0].strip()


def _as_list(value: Any):
    if value is None:
        return []
    if isinstance(value, list):
        return list(value)
    if isinstance(value, tuple):
        return list(value)
    if isinstance(value, str):
        return [value] if value.strip() else []
    return [value]


def _as_string(value: Any) -> str:
    if value is None:
        return ""
    return str(value)
